# Generated by Django 5.2.17 on 2026-09-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0002_itemsource_external_identity_unique"),
        ("tasks", "0002_task_status"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="task",
            name="task_status_valid",
        ),
        migrations.AddField(
            model_name="task",
            name="deadline_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="end_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="grace_period_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="task",
            name="is_all_day",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("urgent_important", "Urgent and important"),
                    ("important", "Important"),
                    ("urgent", "Urgent"),
                    ("none", "None"),
                ],
                default="none",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "Todo"),
                    ("overdue", "Overdue"),
                    ("missed", "Missed"),
                    ("done", "Done"),
                    ("wont_do", "Won't do"),
                    ("skipped", "Skipped"),
                ],
                default="todo",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["todo", "overdue", "missed", "done", "wont_do", "skipped"])
                ),
                name="task_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("priority__in", ["urgent_important", "important", "urgent", "none"])
                ),
                name="task_priority_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_at__isnull", True),
                    models.Q(("due_at__isnull", False), ("end_at__gte", models.F("due_at"))),
                    _connector="OR",
                ),
                name="task_end_after_due",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("deadline_at__isnull", True),
                    ("due_at__isnull", True),
                    ("deadline_at__gte", models.F("due_at")),
                    _connector="OR",
                ),
                name="task_deadline_after_due",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("deadline_at__isnull", True),
                    ("end_at__isnull", True),
                    ("deadline_at__gte", models.F("end_at")),
                    _connector="OR",
                ),
                name="task_deadline_after_end",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_all_day", False), ("due_at__isnull", False), _connector="OR"
                ),
                name="task_all_day_has_due",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("deadline_at__isnull", False), ("grace_period_days", 0), _connector="OR"
                ),
                name="task_grace_requires_deadline",
            ),
        ),
    ]
