# Generated by Django 5.2.17 on 2026-09-12

import re

import django.core.validators
from django.db import migrations, models
from django.db.models.functions import Lower


def populate_account_identity(apps, schema_editor):
    user_model = apps.get_model("identity", "User")

    for user in user_model.objects.all().iterator():
        normalized_email = user.email.strip().lower()
        local_part = normalized_email.split("@", 1)[0]
        stem = re.sub(r"[^A-Za-z0-9_]", "_", local_part).strip("_") or "user"

        user.email = normalized_email
        user.handle = f"{stem[:20]}_{user.id.hex[:8]}"
        user.display_name = local_part[:120] or "Dotick User"
        user.save(update_fields=["email", "handle", "display_name"])


class Migration(migrations.Migration):
    dependencies = [("identity", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="handle",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture_url",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.RunPython(populate_account_identity, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="display_name",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="user",
            name="handle",
            field=models.CharField(
                max_length=30,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message=("Handle must contain 3 to 30 letters, numbers, or underscores."),
                        regex="^[A-Za-z0-9_]{3,30}$",
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                Lower("handle"),
                name="identity_user_handle_ci_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("handle__regex", "^[A-Za-z0-9_]{3,30}$")),
                name="identity_user_handle_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("display_name", ""), _negated=True),
                name="identity_user_display_name_nonempty",
            ),
        ),
    ]
