# Generated by Django 5.2.17 on 2026-09-12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import dotick.identity.validators


class Migration(migrations.Migration):
    dependencies = [("identity", "0002_account_identity")]

    operations = [
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="preferences",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        max_length=64,
                        validators=[dotick.identity.validators.validate_iana_timezone],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "user_preferences"},
        )
    ]
