# Generated by Django 5.2.17 on 2026-09-12

from django.db import migrations, models
from django.db.models.functions import Lower, Trim


class Migration(migrations.Migration):
    dependencies = [("identity", "0004_verification_challenge")]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("email", Trim(Lower("email")))),
                name="identity_user_email_normalized",
            ),
        )
    ]
