# Generated by Django 5.2.17 on 2026-09-14 20:58

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0008_passkeycredential"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasskeyChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("registration", "Registration"),
                            ("authentication", "Authentication"),
                        ],
                        max_length=32,
                    ),
                ),
                ("challenge", models.BinaryField(unique=True)),
                ("name", models.CharField(blank=True, max_length=120)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passkey_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "identity_passkey_challenges",
                "indexes": [
                    models.Index(
                        fields=["purpose", "expires_at"], name="identity_passkey_challenge"
                    )
                ],
            },
        ),
    ]
