# Generated by Django 5.2.17 on 2026-09-14 21:08

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0010_accountcontact"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactVerificationChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code_digest", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_challenges",
                        to="identity.accountcontact",
                    ),
                ),
            ],
            options={
                "db_table": "identity_contact_verification_challenges",
                "indexes": [
                    models.Index(
                        fields=["contact", "-created_at"], name="identity_contact_challenge"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("failed_attempts__lte", 5)),
                        name="identity_contact_attempts_lte_5",
                    )
                ],
            },
        ),
    ]
