# Generated by Django 5.2.17 on 2026-08-09 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('baseevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.baseevent')),
                ('user_status', models.CharField(blank=True, choices=[('DONE', 'Done'), ('WONT_DO', "Won't Do")], default=None, max_length=16, null=True)),
                ('period_end', models.DateTimeField(help_text="When this occurrence's period elapses without action, it becomes AUTO_WONT_DO (§4.6).")),
            ],
            options={
                'db_table': 'routines',
            },
            bases=('core.baseevent',),
        ),
    ]
